### ISSUE TITLE
Social API

### ISSUE THREAD

**Issue by Fraccaman** [Fraccaman/USI-Social-Wall#1]
Need to fetch data by:

- Social Network ( Twitter )
- Hashtag

**Comment by Fraccaman** [comment]
So, guys the problem here is that making a full API from 0 is very difficult. Instead we can use some modules already done ( still difficult  but less ), but i dont know how much modular this will be. What do you think?

**Comment by Fraccaman** [comment]
I've managed to do it with the help of a module but still I don't know if this is quite "legal".

**Comment by framtk** [comment]
what do you mean by "not being legal"?

**Comment by Fraccaman** [comment]
I mean that its not modular because if Twitter changes the API then if the module owner doesn't update them we are fuc*** :)

**Comment by cruzas** [comment]
Do you mean that you managed to do what we were attempting to do with the modules that you found?

**Comment by Fraccaman** [comment]
More or less, because for some reason it show only particular tweets not everyone. Tomorrow we will talk about it.

**Comment by Fraccaman** [comment]
Okay,I've understand how the API of twitter are working. We need to modify something. Also we can't have the data that are older than 7 days. So i think we need to store them in a database or something.

**Comment by Fraccaman** [comment]
In commit 3e4be8864d17b7ddbf817dda5283d8df24b936e7 80% is done. We just need to add more options.
